import ProgressBarComponents from "@/app/components/progressBarComponents";
import Link from "next/link";

export default function CardCharities(){
    return (
        <>
            <Link href="/charities/42yULuEbDeMUsAz7BTAM" style={{boxSizing: 'border-box', outlineWidth: '0px', background: 'rgb(255, 255, 255) none repeat scroll 0% 0% / auto padding-box border-box', transform: 'matrix(1.03, 0, 0, 1.03, 0, 0)', outline: 'rgb(0, 0, 0) none 0px', WebkitTapHighlightColor: 'rgba(0, 0, 0, 0)', display: 'block', textDecoration: 'none solid rgb(0, 0, 0)', color: 'rgb(0, 0, 0)', borderRadius: '8px', boxShadow: 'rgba(0, 0, 0, 0.05) 0px 1px 3px 0px, rgba(0, 0, 0, 0.05) 0px 20px 25px -5px, rgba(0, 0, 0, 0.04) 0px 10px 10px -5px', border: '1px solid rgb(222, 226, 230)', position: 'relative', overflow: 'hidden', backgroundColor: 'rgb(255, 255, 255)', padding: '16px', height: '478.531px'}}>
                <div data-first="true" style={{boxSizing: 'border-box', marginTop: '-16px', borderTop: '0px none rgb(0, 0, 0)', display: 'block', marginLeft: '-16px', marginRight: '-16px'}}>
                    <div style={{width: '100%', boxSizing: 'border-box'}}>
                        <figure style={{boxSizing: 'border-box', display: 'block', margin: '0px'}}>
                            <div style={{boxSizing: 'border-box', position: 'relative'}}><img src="https://i.imgur.com/DNs5fZW.jpg" alt="fundraiser image" style={{objectFit: 'cover', width: '100%', height: '200px', boxSizing: 'border-box', borderStyle: 'none', verticalAlign: 'middle', fontFamily: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji"', display: 'block', border: '0px none rgb(0, 0, 0)', borderRadius: '0px'}} /></div>
                        </figure>
                    </div>
                </div>
                <div style={{boxSizing: 'border-box', display: 'block', marginLeft: '-16px', marginRight: '-16px', borderBottom: '1px solid rgb(222, 226, 230)', paddingLeft: '16px', paddingRight: '16px', paddingBottom: '16px', marginTop: '16px'}}>
                    <div style={{boxSizing: 'border-box', display: 'flex', flexFlow: 'row wrap', WebkitBoxAlign: 'center', alignItems: 'center', WebkitBoxPack: 'justify', justifyContent: 'space-between', gap: '16px'}}>
                        <div style={{boxSizing: 'border-box', fontFamily: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji"', WebkitTapHighlightColor: 'rgba(0, 0, 0, 0)', color: 'rgb(0, 0, 0)', fontSize: '18px', lineHeight: '27.9px', textDecoration: 'none solid rgb(0, 0, 0)', fontWeight: 700, WebkitBoxFlex: 0, flexGrow: 0}}>Rainforest Foundation</div>
                    </div>
                    <div style={{boxSizing: 'border-box', display: 'flex', flexFlow: 'row wrap', WebkitBoxAlign: 'center', alignItems: 'center', WebkitBoxPack: 'start', justifyContent: 'flex-start', gap: '16px'}}>
                        <div style={{boxSizing: 'border-box', fontFamily: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji"', WebkitTapHighlightColor: 'rgba(0, 0, 0, 0)', color: 'rgb(134, 142, 150)', fontSize: '14px', lineHeight: '21.7px', textDecoration: 'none solid rgb(134, 142, 150)', fontWeight: 500, marginTop: '5px', marginBottom: '12px', WebkitBoxFlex: 0, flexGrow: 0}}>Protecting The Rainforest</div>
                    </div>
                    <div style={{boxSizing: 'border-box', display: 'flex', flexFlow: 'row wrap', WebkitBoxAlign: 'center', alignItems: 'center', WebkitBoxPack: 'start', justifyContent: 'flex-start', gap: '4px', marginBottom: '12px'}}>
                        <div style={{boxSizing: 'border-box', WebkitTapHighlightColor: 'rgba(0, 0, 0, 0)', fontFamily: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji"', fontSize: '11px', height: '20px', lineHeight: '18px', textDecoration: 'none solid rgb(64, 192, 87)', padding: '0px 10.6667px', display: 'flex', WebkitBoxAlign: 'center', alignItems: 'center', WebkitBoxPack: 'center', justifyContent: 'center', width: 'auto', textTransform: 'uppercase', borderRadius: '4px', fontWeight: 700, letterSpacing: '0.25px', cursor: 'pointer', textOverflow: 'ellipsis', overflow: 'hidden', background: 'rgb(235, 251, 238) none repeat scroll 0% 0% / auto padding-box border-box', color: 'rgb(64, 192, 87)', border: '1px solid rgba(0, 0, 0, 0)', WebkitBoxFlex: 0, flexGrow: 0}}><span style={{boxSizing: 'border-box', whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis'}}>charity</span></div>
                        <div style={{boxSizing: 'border-box', WebkitTapHighlightColor: 'rgba(0, 0, 0, 0)', fontFamily: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji"', fontSize: '10px', height: '18px', lineHeight: '16px', textDecoration: 'none solid rgb(134, 142, 150)', padding: '0px 8px', display: 'flex', WebkitBoxAlign: 'center', alignItems: 'center', WebkitBoxPack: 'center', justifyContent: 'center', width: 'auto', textTransform: 'uppercase', borderRadius: '4px', fontWeight: 700, letterSpacing: '0.25px', cursor: 'pointer', textOverflow: 'ellipsis', overflow: 'hidden', background: 'rgb(248, 249, 250) none repeat scroll 0% 0% / auto padding-box border-box', color: 'rgb(134, 142, 150)', border: '1px solid rgba(0, 0, 0, 0)', WebkitBoxFlex: 0, flexGrow: 0}}><span style={{boxSizing: 'border-box', whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis'}}>IRL</span></div>
                        <div style={{boxSizing: 'border-box', WebkitTapHighlightColor: 'rgba(0, 0, 0, 0)', fontFamily: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji"', fontSize: '10px', height: '18px', lineHeight: '16px', textDecoration: 'none solid rgb(134, 142, 150)', padding: '0px 8px', display: 'flex', WebkitBoxAlign: 'center', alignItems: 'center', WebkitBoxPack: 'center', justifyContent: 'center', width: 'auto', textTransform: 'uppercase', borderRadius: '4px', fontWeight: 700, letterSpacing: '0.25px', cursor: 'pointer', textOverflow: 'ellipsis', overflow: 'hidden', background: 'rgb(248, 249, 250) none repeat scroll 0% 0% / auto padding-box border-box', color: 'rgb(134, 142, 150)', border: '1px solid rgba(0, 0, 0, 0)', WebkitBoxFlex: 0, flexGrow: 0}}><span style={{boxSizing: 'border-box', whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis'}}>Humanitarian</span></div>
                    </div>
                    <div style={{boxSizing: 'border-box', fontFamily: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji"', WebkitTapHighlightColor: 'rgba(0, 0, 0, 0)', color: 'rgb(134, 142, 150)', fontSize: '14px', lineHeight: '21.7px', textDecoration: 'none solid rgb(134, 142, 150)', marginTop: '10px'}}>The mission of the Rainforest Foundation is to support indigenous and traditional peoples of the wor...</div>
                </div>
                <div data-last="true" style={{boxSizing: 'border-box', marginBottom: '-16px', borderBottom: '0px none rgb(0, 0, 0)', display: 'block', marginLeft: '-16px', marginRight: '-16px', paddingLeft: '16px', paddingRight: '16px', paddingBottom: '16px'}}>
                    <div style={{boxSizing: 'border-box', display: 'flex', flexFlow: 'row wrap', WebkitBoxPack: 'start', justifyContent: 'flex-start', gap: '5px', WebkitBoxAlign: 'center', alignItems: 'center', marginTop: '16px', marginBottom: '12px'}}>
                        <div style={{boxSizing: 'border-box', fontFamily: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji"', WebkitTapHighlightColor: 'rgba(0, 0, 0, 0)', color: 'rgb(0, 0, 0)', fontSize: '18px', lineHeight: '27.9px', textDecoration: 'none solid rgb(0, 0, 0)', fontWeight: 700, WebkitBoxFlex: 0, flexGrow: 0}}>1.40</div>
                        <div style={{boxSizing: 'border-box', fontFamily: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji"', WebkitTapHighlightColor: 'rgba(0, 0, 0, 0)', color: 'rgb(134, 142, 150)', lineHeight: '12px', textDecoration: 'none solid rgb(134, 142, 150)', textAlign: 'justify', textTransform: 'uppercase', fontSize: '12px', fontWeight: 700, paddingTop: '2px', WebkitBoxFlex: 0, flexGrow: 0}}>SOL raised</div>
                    </div>
                    {/*<div style={{boxSizing: 'border-box', position: 'relative', height: '8px', backgroundColor: 'rgb(233, 236, 239)', borderRadius: '4px', overflow: 'hidden'}}>*/}
                    {/*    <div style={{width: '0.7%', boxSizing: 'border-box', borderTopLeftRadius: '4px', borderBottomLeftRadius: '4px', borderTopRightRadius: '4px', borderBottomRightRadius: '4px', position: 'absolute', top: '0px', bottom: '0px', left: '0px', height: '8px', display: 'flex', WebkitBoxPack: 'center', justifyContent: 'center', WebkitBoxAlign: 'center', alignItems: 'center', backgroundColor: 'rgb(253, 126, 20)', transition: 'width 0.1s linear 0s', animation: '1s linear 0s infinite normal none running animation-1mos065', backgroundSize: '20px 20px', backgroundImage: 'linear-gradient(45deg, rgba(255, 255, 255, 0.15) 25%, rgba(0, 0, 0, 0) 25%, rgba(0, 0, 0, 0) 50%, rgba(255, 255, 255, 0.15) 50%, rgba(255, 255, 255, 0.15) 75%, rgba(0, 0, 0, 0) 75%, rgba(0, 0, 0, 0))'}}></div>*/}
                    {/*</div>*/}
                    <ProgressBarComponents rate="17.7" />
                </div>
            </Link>
        </>
    )
}